import { Course } from "@/types";

export const courses: Course[] = [
  {
    id: "react-developer-bootcamp",
    title: "React Developer Bootcamp",
    description:
      "Master React.js from fundamentals to advanced concepts. This comprehensive 8-week bootcamp covers React hooks, context, routing, and state management. Build real-world applications with best practices, performance optimizations, and testing techniques to prepare you for professional React development roles.",
    category: "Frontend Development",
    level: "Intermediate",
    duration: "8 weeks",
    price: 300,
    originalPrice: 400,
    instructor: "Aboderin Daniel",
    instructorBio:
      "Senior Frontend Engineer with 8+ years of React experience. Expert in scalable application architecture and user-centric UI development. Passionate about mentoring and open source contributions.",
    rating: 4.9,
    studentsEnrolled: 12847,
    image:
      "https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=800",
    skills: [
      "React.js fundamentals",
      "JavaScript ES6+",
      "JSX and component architecture",
      "React Hooks (useState, useEffect, useContext)",
      "Context API for global state",
      "React Router for client-side routing",
      "State management patterns",
      "Component design best practices",
      "Performance optimization",
      "Testing with Jest and React Testing Library",
      "Deployment and build optimization",
    ],
    prerequisites: [
      "Basic JavaScript knowledge including ES6 syntax",
      "Understanding of HTML & CSS fundamentals",
      "Familiarity with asynchronous programming (Promises, async/await)",
    ],
    curriculum: [
      {
        module: "React Fundamentals",
        lessons: [
          "Introduction to React and Virtual DOM concepts",
          "Creating Functional and Class Components",
          "JSX Syntax and Component Composition",
          "Props and Component Communication Patterns",
          "Handling Events and Forms in React",
          "React Developer Tools and Debugging",
        ],
      },
      {
        module: "State Management & Hooks",
        lessons: [
          "State vs Props Deep Dive",
          "Using useState for Local Component State",
          "Effect Hook (useEffect) for Side Effects and Lifecycle",
          "Custom Hooks: Building Reusable Logic",
          "Global State Management with useContext",
          "Introduction to useReducer for Complex State",
        ],
      },
      {
        module: "Advanced React Patterns",
        lessons: [
          "Higher-Order Components (HOCs) Explained",
          "Render Props Pattern for Component Reuse",
          "Compound Components and Controlled Components",
          "React.memo and useCallback for Performance",
          "Error Boundaries and Graceful Degradation",
          "Code Splitting and Lazy Loading Components",
        ],
      },
      {
        module: "Routing & Navigation",
        lessons: [
          "React Router Setup and Configuration",
          "Dynamic Routing and Nested Routes",
          "Protected Routes and Authentication Guards",
          "URL Parameters, Query Strings, and Redirects",
          "Programmatic Navigation and Route Hooks",
          "Handling 404 and Fallback Routes",
        ],
      },
      {
        module: "Real-World Project",
        lessons: [
          "Planning and Architecting a Task Management App",
          "Building Interactive UI with React Components",
          "Integrating REST APIs with Axios/Fetch",
          "Managing Global State and Context",
          "Testing Components with Jest and RTL",
          "Performance Optimization and Code Cleanup",
          "Deployment to Netlify, Vercel, or AWS",
        ],
      },
    ],
    whatYouWillLearn: [
      "Build modern, scalable React applications from scratch",
      "Master functional components and React Hooks",
      "Implement advanced state management patterns",
      "Create reusable, maintainable component libraries",
      "Integrate APIs and handle async operations effectively",
      "Set up client-side routing with React Router",
      "Write unit and integration tests for React apps",
      "Deploy React apps with best practices for production",
    ],
    features: [
      "40+ hours of HD video content with downloadable resources",
      "15 hands-on coding projects with real-world scenarios",
      "Live weekly coding sessions with Q&A",
      "Peer code reviews and personalized feedback",
      "Access to private Discord community for networking",
      "Career coaching including interview prep and resume reviews",
    ],
    certificate: true,
    support: "24/7 instructor and mentor support via chat and email",
    access: "Lifetime access to course materials with free updates",
  },
  {
    id: "python-data-science",
    title: "Python for Data Science",
    description:
      "Start your data science journey with Python! This beginner-friendly 10-week course teaches you Python programming, data manipulation, visualization, and machine learning fundamentals. Gain hands-on experience analyzing real datasets, preparing data for analysis, and building predictive models using popular libraries.",
    category: "Data Science",
    level: "Beginner",
    duration: "10 weeks",
    price: 200,
    originalPrice: 300,
    instructor: "Okechukwu Kingsley",
    instructorBio:
      "Data Science Lead. Has published over 20 research papers on machine learning and data analysis techniques. Experienced mentor and industry consultant.",
    rating: 4.8,
    studentsEnrolled: 8934,
    image:
      "https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=800",
    skills: [
      "Python programming basics",
      "Pandas for data manipulation",
      "NumPy for numerical computing",
      "Matplotlib and Seaborn for visualization",
      "Data cleaning and preprocessing",
      "Statistical analysis and hypothesis testing",
      "Exploratory Data Analysis (EDA)",
      "Jupyter Notebooks for interactive coding",
      "Introduction to machine learning concepts",
      "Basic predictive modeling",
    ],
    prerequisites: [
      "Basic computer literacy",
      "High school level mathematics (algebra, statistics)",
      "No prior programming experience required",
    ],
    curriculum: [
      {
        module: "Python Fundamentals",
        lessons: [
          "Installing Python and Jupyter Notebook Setup",
          "Variables, Data Types, and Basic Operators",
          "Control Flow: Conditionals and Loops",
          "Functions, Modules, and Packages",
          "File Input/Output and Exception Handling",
          "Introduction to Object-Oriented Programming",
        ],
      },
      {
        module: "Data Manipulation with Pandas",
        lessons: [
          "Introduction to Pandas DataFrames and Series",
          "Loading, Inspecting, and Exporting Data",
          "Data Cleaning: Handling Missing and Duplicate Data",
          "Data Transformation: Filtering, Sorting, and Grouping",
          "Merging, Joining, and Concatenating DataFrames",
          "Time Series Data Handling",
        ],
      },
      {
        module: "Numerical Computing with NumPy",
        lessons: [
          "Creating and Manipulating NumPy Arrays",
          "Mathematical and Statistical Functions",
          "Broadcasting and Vectorization Techniques",
          "Linear Algebra and Matrix Operations",
          "Random Number Generation and Simulations",
          "Performance Optimization Using NumPy",
        ],
      },
      {
        module: "Data Visualization",
        lessons: [
          "Basic Plotting with Matplotlib",
          "Creating Line, Bar, Scatter, and Histogram Charts",
          "Advanced Visualizations with Seaborn",
          "Customizing Plots and Themes",
          "Interactive Visualizations using Plotly",
          "Building Dashboards for Data Presentation",
        ],
      },
      {
        module: "Real-World Data Projects",
        lessons: [
          "Exploratory Data Analysis on Public Datasets",
          "Sales and Revenue Data Analysis Case Study",
          "Customer Segmentation with Clustering Techniques",
          "Introduction to Time Series Analysis",
          "Final Capstone Project: End-to-End Data Science Workflow",
        ],
      },
    ],
    whatYouWillLearn: [
      "Write efficient Python code for data analysis",
      "Manipulate large datasets using Pandas and NumPy",
      "Visualize data insights with Matplotlib and Seaborn",
      "Perform statistical analysis to validate hypotheses",
      "Clean and preprocess raw data for analysis",
      "Explore real-world datasets to uncover patterns",
      "Build basic machine learning models",
      "Present findings via interactive dashboards",
    ],
    features: [
      "50+ hours of structured video lectures and exercises",
      "20 real-world datasets for hands-on practice",
      "Fully functional Jupyter notebook templates",
      "Weekly live Q&A sessions with instructor",
      "Assignments reviewed by industry mentors",
      "Job placement assistance and career advice",
    ],
    certificate: true,
    support: "Instructor support available during business hours",
    access: "Lifetime access to course content and updates",
  },
  {
    id: "fullstack-javascript",
    title: "Full-Stack JavaScript Mastery",
    description:
      "Become a professional full-stack developer in 12 weeks! Learn backend development with Node.js and Express, frontend with React, and database management with MongoDB. Build scalable, secure, and production-ready applications, deploy to cloud platforms, and understand DevOps essentials.",
    category: "Full-Stack Development",
    level: "Advanced",
    duration: "12 weeks",
    price: 300,
    originalPrice: 400,
    instructor: "Aboderin Daniel",
    instructorBio:
      "Full-Stack Architect  with over 5 years of experience. Expert in scalable system design, cloud infrastructure, and open-source contributions. Passionate about teaching and mentoring developers.",
    rating: 4.9,
    studentsEnrolled: 6721,
    image:
      "https://images.pexels.com/photos/1181244/pexels-photo-1181244.jpeg?auto=compress&cs=tinysrgb&w=800",
    skills: [
      "Node.js server-side programming",
      "Express.js framework and middleware",
      "React.js advanced frontend development",
      "MongoDB database design and querying",
      "RESTful API design and GraphQL",
      "User authentication and authorization",
      "Docker containerization",
      "CI/CD pipeline setup",
      "Cloud deployment (AWS, Heroku)",
      "Monitoring, logging, and performance tuning",
    ],
    prerequisites: [
      "Strong JavaScript (ES6+) proficiency",
      "Basic understanding of React",
      "Knowledge of HTTP, REST, and APIs",
      "Experience with Git and version control",
    ],
    curriculum: [
      {
        module: "Backend Development with Node.js",
        lessons: [
          "Node.js Fundamentals and Event Loop",
          "Creating RESTful APIs with Express.js",
          "Middleware Design and Error Handling",
          "Working with MongoDB and Mongoose ODM",
          "Implementing JWT and OAuth Authentication",
          "Building Secure and Scalable Backend Services",
        ],
      },
      {
        module: "Advanced Frontend with React",
        lessons: [
          "Advanced Component Patterns and Hooks",
          "State Management with Redux and Context API",
          "Performance Tuning and Memoization",
          "Testing with Jest and React Testing Library",
          "Building Progressive Web Apps (PWAs)",
          "Code Splitting and Lazy Loading Techniques",
        ],
      },
      {
        module: "Database Design & Management",
        lessons: [
          "MongoDB Data Modeling and Schema Design",
          "Aggregation Framework and Pipelines",
          "Indexing and Query Optimization",
          "Backup, Restore, and Replication",
          "Transactions and ACID Compliance",
          "Database Security Best Practices",
        ],
      },
      {
        module: "API Development & Integration",
        lessons: [
          "RESTful API Design Principles",
          "Building and Using GraphQL APIs",
          "API Documentation with Swagger/OpenAPI",
          "Implementing Rate Limiting and Throttling",
          "Third-party API Integration and Webhooks",
          "API Testing and Monitoring",
        ],
      },
      {
        module: "Deployment & DevOps Essentials",
        lessons: [
          "Introduction to Docker and Containerization",
          "Setting up CI/CD Pipelines with GitHub Actions",
          "Deploying Applications on AWS and Heroku",
          "Monitoring with Prometheus and Grafana",
          "Logging Best Practices",
          "Scaling Applications and Load Balancing",
        ],
      },
      {
        module: "Capstone Project",
        lessons: [
          "Designing a Full-Stack Social Media App",
          "Implementing User Authentication and Profiles",
          "Creating Real-Time Chat with WebSockets",
          "Integrating Payment Gateway APIs",
          "Testing, Debugging, and Optimization",
          "Deployment and Continuous Integration",
        ],
      },
    ],
    whatYouWillLearn: [
      "Develop full-stack applications using JavaScript technologies",
      "Build scalable RESTful and GraphQL APIs",
      "Create dynamic and responsive frontend interfaces",
      "Manage NoSQL databases with MongoDB effectively",
      "Implement secure authentication and authorization",
      "Containerize and deploy applications in the cloud",
      "Setup CI/CD pipelines for automated deployments",
      "Optimize application performance and scalability",
    ],
    features: [
      "60+ hours of in-depth video tutorials and workshops",
      "Comprehensive coding challenges and projects",
      "One-on-one mentorship sessions",
      "Access to private Slack community and career network",
      "Resume reviews and technical interview preparation",
      "Certificate of Completion recognized by industry leaders",
    ],
    certificate: true,
    support: "Dedicated support team available weekdays 9am–6pm",
    access: "Lifetime access with free course material updates",
  },
  {
    id: "cybersecurity-foundations",
    title: "Cybersecurity Foundations",
    description:
      "Understand the core principles of cybersecurity. This 8-week course covers threat modeling, network security, ethical hacking, cryptography, and incident response. Perfect for beginners aiming to enter the rapidly growing cybersecurity industry.",
    category: "Cybersecurity",
    level: "Beginner",
    duration: "8 weeks",
    price: 250,
    originalPrice: 350,
    instructor: "Adedeji Michael",
    instructorBio:
      "Cybersecurity Consultant with 10+ years of experience. Certified Ethical Hacker (CEH) and CISSP holder with a passion for securing digital infrastructures and mentoring new professionals.",
    rating: 4.8,
    studentsEnrolled: 7265,
    image:
      "https://images.pexels.com/photos/5380659/pexels-photo-5380659.jpeg?auto=compress&cs=tinysrgb&w=800",
    skills: [
      "Cybersecurity fundamentals",
      "Network and system security",
      "Threat analysis and mitigation",
      "Security tools (Wireshark, Metasploit)",
      "Introduction to cryptography",
      "Incident response planning",
      "Ethical hacking basics",
      "Vulnerability assessment",
    ],
    prerequisites: [
      "Basic IT knowledge",
      "Familiarity with operating systems",
      "No prior cybersecurity experience required",
    ],
    curriculum: [
      {
        module: "Security Principles & Threats",
        lessons: [
          "Introduction to Cybersecurity and Threat Landscape",
          "Security Goals: Confidentiality, Integrity, Availability",
          "Types of Cyber Threats and Vulnerabilities",
          "Malware, Phishing, and Social Engineering",
        ],
      },
      {
        module: "Network & System Security",
        lessons: [
          "Understanding TCP/IP and Firewalls",
          "Network Monitoring and Intrusion Detection Systems (IDS)",
          "System Hardening and Patch Management",
          "Linux and Windows Security Basics",
        ],
      },
      {
        module: "Ethical Hacking & Cryptography",
        lessons: [
          "Footprinting and Reconnaissance",
          "Scanning and Enumeration",
          "Introduction to Encryption and Hashing",
          "Public Key Infrastructure (PKI)",
        ],
      },
      {
        module: "Incident Response & Final Project",
        lessons: [
          "Incident Response Lifecycle",
          "Security Policies and Compliance (GDPR, ISO)",
          "Simulated Breach Response Scenario",
          "Final Capstone: Investigate and Defend a Cyber Attack",
        ],
      },
    ],
    whatYouWillLearn: [
      "Build foundational cybersecurity knowledge",
      "Use common cybersecurity tools",
      "Understand and analyze cyber threats",
      "Create basic incident response plans",
      "Gain exposure to ethical hacking concepts",
      "Learn how cryptographic systems protect data",
    ],
    features: [
      "40+ hours of training content",
      "Hands-on labs in virtual environments",
      "Weekly real-world security case studies",
      "Mock interviews and certification prep",
      "Dedicated Discord community",
    ],
    certificate: true,
    support: "Live office hours and community forum access",
    access: "Lifetime access with future updates included",
  },
  {
    id: "product-management-essentials",
    title: "Product Management Essentials",
    description:
      "Learn how to build and manage successful products from ideation to launch. This 6-week course covers user research, MVP development, agile workflows, roadmapping, and stakeholder communication, designed for aspiring and junior product managers.",
    category: "Product Management",
    level: "Beginner",
    duration: "6 weeks",
    price: 200,
    originalPrice: 300,
    instructor: "Okechukwu Kingsley",
    instructorBio:
      "Senior Product Manager  with a decade of experience building customer-first digital experiences. Former UX researcher turned product strategist focused on outcome-driven development.",
    rating: 4.7,
    studentsEnrolled: 4021,
    image:
      "https://images.pexels.com/photos/3184325/pexels-photo-3184325.jpeg?auto=compress&cs=tinysrgb&w=800",
    skills: [
      "Product lifecycle management",
      "Agile methodologies (Scrum/Kanban)",
      "Roadmapping and release planning",
      "User research and persona development",
      "Stakeholder communication",
      "Minimum Viable Product (MVP) design",
      "KPIs and product metrics",
      "Cross-functional team leadership",
    ],
    prerequisites: [
      "Basic understanding of business or tech concepts",
      "No prior product management experience required",
    ],
    curriculum: [
      {
        module: "Introduction to Product Management",
        lessons: [
          "What is Product Management?",
          "PM Roles and Responsibilities",
          "Key Product Metrics and KPIs",
        ],
      },
      {
        module: "User-Centered Product Development",
        lessons: [
          "Conducting User Research and Surveys",
          "Creating Personas and Journey Maps",
          "Validating Product Ideas",
        ],
      },
      {
        module: "Agile Development and Roadmapping",
        lessons: [
          "Scrum vs Kanban",
          "Backlog Grooming and Sprint Planning",
          "Writing Effective User Stories",
          "Creating and Prioritizing Roadmaps",
        ],
      },
      {
        module: "Launch Strategy & Final Pitch",
        lessons: [
          "Go-to-Market Planning",
          "Managing Stakeholders and Engineers",
          "Final Capstone: Build and Pitch Your Product",
        ],
      },
    ],
    whatYouWillLearn: [
      "Understand the full product lifecycle",
      "Lead agile product development processes",
      "Translate user insights into product ideas",
      "Communicate effectively with stakeholders",
      "Prioritize features using industry best practices",
      "Design a compelling product pitch",
    ],
    features: [
      "30+ hours of course material",
      "Project-based assignments and final pitch",
      "Case studies from top tech companies",
      "Live mentor sessions weekly",
      "Certificate portfolio-ready project",
    ],
    certificate: true,
    support: "Slack and email support with weekly Q&A",
    access: "Lifetime access with downloadable templates",
  },
];
